/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Pesan_Makan extends javax.swing.JFrame {
    private int jumlahBeli = 0;
    private String pesanan = "";
    
    private class MenuItem {
        String name;
        int price;

        MenuItem(String name, int price) {
            this.name = name;
            this.price = price;
        }
    }
    
    // Create an array to store menu items
    // membuat array 
    private MenuItem[] menuItems = {
        new MenuItem("Rawon", 12000),
        new MenuItem("Bakso", 10000),
        new MenuItem("Sate", 17000),
        new MenuItem("Nasi Pecel", 25000),
        new MenuItem("Nasi Rames", 18000),
        new MenuItem("Nasi Kuning", 10000),
        new MenuItem("Rendang", 25000),
        new MenuItem("Ayam Bakar", 20000),
        new MenuItem("Nasi Goreng", 15000),
        new MenuItem("Soto Ayam", 20000),
        new MenuItem("Seblak", 15000),
        new MenuItem("Mie Ayam", 17000),
        
        // Add more menu items with their prices
    };
    private String getSelectedMenu() {
    if (rbRawon.isSelected()) {
        return "Rawon";
    } else if (rbBakso.isSelected()) {
        return "Bakso";
    } else if (rbSotoAyam.isSelected()) {
        return "Soto Ayam";
    } else if (rbSate.isSelected()) {
        return "Sate";
    } else if (rbNasiGroreng.isSelected()) {
        return "Nasi Goreng";
    } else if (rbNasiKuning.isSelected()) {
        return "Nasi Kuning";
    } else if (rbNasiRames.isSelected()) {
        return "Nasi Rames";
    } else if (rbRendang.isSelected()) {
        return "Rendang";
    } else if (rbSeblak.isSelected()) {
        return "Seblak";
    } else if (rbNasiPecel.isSelected()) {
        return "Nasi Pecel";
    } else if (rbAyamBakar.isSelected()) {
        return "Ayam Bakar";
    } else if (rbMieAyam.isSelected()) {
        return "Mie Ayam";
    } else {
        // Handle the case where no radio button is selected
        JOptionPane.showMessageDialog(this, "Pilih menu terlebih dahulu");
        return null;
    }
}
    
    /**
     * Creates new form Pesan_Makan
     */
    public Pesan_Makan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        bgMakanan = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblJumlahBeli = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        bKurang = new javax.swing.JButton();
        txtJumlahBeli = new javax.swing.JTextField();
        lblInformasiPesanan = new javax.swing.JLabel();
        bBeli = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        lblPesanan = new javax.swing.JLabel();
        txtPesanan = new javax.swing.JTextField();
        lblJumlah = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();
        rbRawon = new javax.swing.JRadioButton();
        rbBakso = new javax.swing.JRadioButton();
        rbSotoAyam = new javax.swing.JRadioButton();
        rbSate = new javax.swing.JRadioButton();
        rbNasiGroreng = new javax.swing.JRadioButton();
        rbNasiKuning = new javax.swing.JRadioButton();
        rbNasiRames = new javax.swing.JRadioButton();
        rbRendang = new javax.swing.JRadioButton();
        rbSeblak = new javax.swing.JRadioButton();
        rbNasiPecel = new javax.swing.JRadioButton();
        rbAyamBakar = new javax.swing.JRadioButton();
        rbMieAyam = new javax.swing.JRadioButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WAROENG");

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        jLabel2.setText("MAKAN AJA!");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_2/icon_RM_2-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 360, 120);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        lblJumlahBeli.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lblJumlahBeli.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlahBeli.setText("Jumlah Beli");

        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bTambah.setForeground(new java.awt.Color(0, 0, 153));
        bTambah.setText("+");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bKurang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bKurang.setText("-");
        bKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKurangActionPerformed(evt);
            }
        });

        txtJumlahBeli.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtJumlahBeli.setForeground(new java.awt.Color(0, 51, 204));
        txtJumlahBeli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJumlahBeli.setText("0");
        txtJumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBeliActionPerformed(evt);
            }
        });

        lblInformasiPesanan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInformasiPesanan.setForeground(new java.awt.Color(255, 255, 255));
        lblInformasiPesanan.setText("Informasi Pesanan");

        bBeli.setForeground(new java.awt.Color(0, 51, 204));
        bBeli.setText("BELI");
        bBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBeliActionPerformed(evt);
            }
        });

        bHapus.setForeground(new java.awt.Color(0, 51, 204));
        bHapus.setText("HAPUS");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        lblPesanan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPesanan.setForeground(new java.awt.Color(255, 255, 255));
        lblPesanan.setText("Pesanan");

        txtPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesananActionPerformed(evt);
            }
        });

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlah.setForeground(new java.awt.Color(255, 255, 255));
        lblJumlah.setText("Jumlah");

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total");

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(lblJumlahBeli))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(bBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(bHapus))
                                .addComponent(lblInformasiPesanan)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblJumlah)
                                .addComponent(lblPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotal))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(txtPesanan))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(bExit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblJumlahBeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(txtJumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInformasiPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBeli)
                    .addComponent(bHapus))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesanan)
                    .addComponent(txtPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal))
                .addGap(38, 38, 38)
                .addComponent(bExit)
                .addGap(23, 23, 23))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(360, 0, 240, 420);

        bgMakanan.add(rbRawon);
        rbRawon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbRawon.setForeground(new java.awt.Color(0, 102, 204));
        rbRawon.setText("Rawon");
        rbRawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRawonActionPerformed(evt);
            }
        });
        jPanel1.add(rbRawon);
        rbRawon.setBounds(20, 180, 80, 20);

        bgMakanan.add(rbBakso);
        rbBakso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbBakso.setForeground(new java.awt.Color(0, 102, 204));
        rbBakso.setText("Bakso");
        rbBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBaksoActionPerformed(evt);
            }
        });
        jPanel1.add(rbBakso);
        rbBakso.setBounds(20, 230, 60, 21);

        bgMakanan.add(rbSotoAyam);
        rbSotoAyam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbSotoAyam.setForeground(new java.awt.Color(0, 102, 204));
        rbSotoAyam.setText("Soto Ayam");
        rbSotoAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSotoAyamActionPerformed(evt);
            }
        });
        jPanel1.add(rbSotoAyam);
        rbSotoAyam.setBounds(250, 230, 98, 30);

        bgMakanan.add(rbSate);
        rbSate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbSate.setForeground(new java.awt.Color(0, 102, 204));
        rbSate.setText("Sate");
        rbSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSateActionPerformed(evt);
            }
        });
        jPanel1.add(rbSate);
        rbSate.setBounds(20, 280, 60, 21);

        bgMakanan.add(rbNasiGroreng);
        rbNasiGroreng.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbNasiGroreng.setForeground(new java.awt.Color(0, 102, 204));
        rbNasiGroreng.setText("Nasi Goreng");
        rbNasiGroreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNasiGrorengActionPerformed(evt);
            }
        });
        jPanel1.add(rbNasiGroreng);
        rbNasiGroreng.setBounds(250, 180, 91, 21);

        bgMakanan.add(rbNasiKuning);
        rbNasiKuning.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbNasiKuning.setForeground(new java.awt.Color(0, 102, 204));
        rbNasiKuning.setText("Nasi Kuning");
        jPanel1.add(rbNasiKuning);
        rbNasiKuning.setBounds(120, 230, 100, 21);

        bgMakanan.add(rbNasiRames);
        rbNasiRames.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbNasiRames.setForeground(new java.awt.Color(0, 102, 204));
        rbNasiRames.setText("Nasi Rames");
        jPanel1.add(rbNasiRames);
        rbNasiRames.setBounds(120, 180, 86, 21);

        bgMakanan.add(rbRendang);
        rbRendang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbRendang.setForeground(new java.awt.Color(0, 102, 204));
        rbRendang.setText("Rendang");
        rbRendang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRendangActionPerformed(evt);
            }
        });
        jPanel1.add(rbRendang);
        rbRendang.setBounds(120, 280, 80, 21);

        bgMakanan.add(rbSeblak);
        rbSeblak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbSeblak.setForeground(new java.awt.Color(0, 102, 204));
        rbSeblak.setText("Seblak");
        rbSeblak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSeblakActionPerformed(evt);
            }
        });
        jPanel1.add(rbSeblak);
        rbSeblak.setBounds(250, 280, 70, 21);

        bgMakanan.add(rbNasiPecel);
        rbNasiPecel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbNasiPecel.setForeground(new java.awt.Color(0, 102, 204));
        rbNasiPecel.setText("Nasi Pecel");
        rbNasiPecel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNasiPecelActionPerformed(evt);
            }
        });
        jPanel1.add(rbNasiPecel);
        rbNasiPecel.setBounds(20, 330, 90, 21);

        bgMakanan.add(rbAyamBakar);
        rbAyamBakar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbAyamBakar.setForeground(new java.awt.Color(0, 102, 204));
        rbAyamBakar.setText("Ayam Bakar");
        jPanel1.add(rbAyamBakar);
        rbAyamBakar.setBounds(120, 330, 100, 21);

        bgMakanan.add(rbMieAyam);
        rbMieAyam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbMieAyam.setForeground(new java.awt.Color(0, 102, 204));
        rbMieAyam.setText("Mie Ayam");
        rbMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMieAyamActionPerformed(evt);
            }
        });
        jPanel1.add(rbMieAyam);
        rbMieAyam.setBounds(250, 330, 80, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        jumlahBeli++;
        txtJumlahBeli.setText(String.valueOf(jumlahBeli));
    }//GEN-LAST:event_bTambahActionPerformed

    private void txtJumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBeliActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtJumlahBeliActionPerformed

    private void rbRawonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRawonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRawonActionPerformed

    private void rbSotoAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSotoAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSotoAyamActionPerformed

    private void rbNasiGrorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNasiGrorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNasiGrorengActionPerformed

    private void rbRendangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRendangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRendangActionPerformed

    private void rbSeblakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSeblakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSeblakActionPerformed

    private void rbNasiPecelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNasiPecelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNasiPecelActionPerformed

    private void rbBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBaksoActionPerformed

    private void rbSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSateActionPerformed

    private void rbMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMieAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMieAyamActionPerformed

    private void txtPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesananActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void bKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKurangActionPerformed
        // TODO add your handling code here:
        if (jumlahBeli > 0) {
                jumlahBeli--;
                txtJumlahBeli.setText(String.valueOf(jumlahBeli));
            }
    }//GEN-LAST:event_bKurangActionPerformed

  
    private void bBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBeliActionPerformed
        // TODO add your handling code here:
        if (jumlahBeli > 0) {
        String menu = getSelectedMenu();

        
        if (menu != null) {
            
            int hargaPerMenu = getMenuPrice(menu);

            int totalHarga = hargaPerMenu * jumlahBeli;

            
            txtPesanan.setText(menu);
            txtJumlah.setText(String.valueOf(jumlahBeli));
            txtTotal.setText(String.valueOf(totalHarga));
        }
    } else {
        JOptionPane.showMessageDialog(this, "Jumlah beli tidak boleh kurang dari 1");
    }
        
    }//GEN-LAST:event_bBeliActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        txtPesanan.setText("");
        txtJumlah.setText("");
        txtTotal.setText("");
    }//GEN-LAST:event_bHapusActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed
    private int getMenuPrice(String menuName) {
        for (MenuItem menuItem : menuItems) {
            if (menuItem.name.equals(menuName)) {
                return menuItem.price;
            }
        }
        return 0; // Return 0 if the menu is not found (you can handle this case differently)
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesan_Makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesan_Makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesan_Makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesan_Makan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesan_Makan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBeli;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKurang;
    private javax.swing.JButton bTambah;
    private javax.swing.ButtonGroup bgMakanan;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblInformasiPesanan;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblJumlahBeli;
    private javax.swing.JLabel lblPesanan;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbAyamBakar;
    private javax.swing.JRadioButton rbBakso;
    private javax.swing.JRadioButton rbMieAyam;
    private javax.swing.JRadioButton rbNasiGroreng;
    private javax.swing.JRadioButton rbNasiKuning;
    private javax.swing.JRadioButton rbNasiPecel;
    private javax.swing.JRadioButton rbNasiRames;
    private javax.swing.JRadioButton rbRawon;
    private javax.swing.JRadioButton rbRendang;
    private javax.swing.JRadioButton rbSate;
    private javax.swing.JRadioButton rbSeblak;
    private javax.swing.JRadioButton rbSotoAyam;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtJumlahBeli;
    private javax.swing.JTextField txtPesanan;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
